In [1]:
import sys
sys.path.append('..')
import numpy as np
from gravity import g, dgdr, d2gdr2
from scipy.optimize._numdiff import approx_derivative

In [2]:
r = np.array([1., 2., 3.])
g(r)

array([-0.01909009, -0.03818018, -0.05727027])

In [3]:
approx_derivative(
    g, r
) - dgdr(r)

array([[-4.29243446e-13, -6.90397392e-13,  3.83143170e-13],
       [-1.12010574e-12, -1.53645759e-12,  7.66286340e-13],
       [-1.68015775e-12, -2.21442309e-12, -3.80265264e-13]])

In [4]:
dgdr(r)

array([[-0.01499936,  0.00818147,  0.0122722 ],
       [ 0.00818147, -0.00272716,  0.0245444 ],
       [ 0.0122722 ,  0.0245444 ,  0.01772651]])

In [5]:
for i in range(3):
    print(approx_derivative(
        lambda r: dgdr(r)[i], r
    ) - d2gdr2(r)[i])

[[-4.16099447e-13 -4.54057798e-13  8.26075319e-14]
 [ 1.18888406e-13  4.85571435e-13 -6.48814336e-13]
 [-3.65211333e-14  6.37399855e-13 -2.32775604e-13]]
[[ 1.18888406e-13  4.85571435e-13 -6.48814336e-13]
 [-3.73847221e-13  1.63294725e-13 -9.14488103e-13]
 [ 7.09017914e-13  1.45671409e-12 -4.65551209e-13]]
[[-3.65211333e-14  6.37399855e-13 -2.32775604e-13]
 [ 7.09017914e-13  1.45671409e-12 -4.65551209e-13]
 [ 2.17000029e-13  1.43665635e-12  9.27371461e-13]]


In [6]:
d2gdr2(r)

array([[[ 0.01081122,  0.00525951,  0.00788927],
        [ 0.00525951, -0.00175317, -0.00876586],
        [ 0.00788927, -0.00876586, -0.00905805]],

       [[ 0.00525951, -0.00175317, -0.00876586],
        [-0.00175317,  0.01285659, -0.00525951],
        [-0.00876586, -0.00525951, -0.0181161 ]],

       [[ 0.00788927, -0.00876586, -0.00905805],
        [-0.00876586, -0.00525951, -0.0181161 ],
        [-0.00905805, -0.0181161 , -0.00262976]]])

In [7]:
%%timeit
g(r)

1.02 µs ± 4.72 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
%%timeit
dgdr(r)

1.37 µs ± 5.56 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
%%timeit
d2gdr2(r)

1.08 µs ± 5.72 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
